// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDtp5RfEwb9qkRwCFBMV8xQjabYhD6tzI',
    appId: '1:480405326039:web:e98af695b6e76aeaab0892',
    messagingSenderId: '480405326039',
    projectId: 'message-me-416f6',
    authDomain: 'message-me-416f6.firebaseapp.com',
    storageBucket: 'message-me-416f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEgSdXZZ3Vl_N9fNO1B7fEPT9B5pIt5nw',
    appId: '1:480405326039:android:691ad263122e942fab0892',
    messagingSenderId: '480405326039',
    projectId: 'message-me-416f6',
    storageBucket: 'message-me-416f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6ZByvfOqi06OnDOHWNGQ8OcKcdXLggKw',
    appId: '1:480405326039:ios:d61fe8fce91eaa91ab0892',
    messagingSenderId: '480405326039',
    projectId: 'message-me-416f6',
    storageBucket: 'message-me-416f6.appspot.com',
    iosClientId: '480405326039-9k9852tq8g858migdh4vdrfhqtndjm31.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6ZByvfOqi06OnDOHWNGQ8OcKcdXLggKw',
    appId: '1:480405326039:ios:d61fe8fce91eaa91ab0892',
    messagingSenderId: '480405326039',
    projectId: 'message-me-416f6',
    storageBucket: 'message-me-416f6.appspot.com',
    iosClientId: '480405326039-9k9852tq8g858migdh4vdrfhqtndjm31.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageMe',
  );
}
